exclude: "django_twined/static|django_twined/templates|build|node_modules|.git/|.tox|staticfiles|static_files|media_files|((?:[^/]*/)*)(.svg)|((?:[^/]*/)*)(.xml)|.pytest_cache"
default_stages: [commit]
fail_fast: true
default_language_version:
  python: python3 # force all unspecified python hooks to run python3
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.1.0
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=10240"]
      - id: check-yaml
      - id: end-of-file-fixer
      - id: no-commit-to-branch
      - id: trailing-whitespace

  - repo: https://gitlab.com/bmares/check-json5
    rev: v1.0.0
    hooks:
      - id: check-json5

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.0
    hooks:
      - id: ruff
        name: Ruff lint
        args: [--fix, --exit-non-zero-on-fix]

      - id: ruff
        name: Ruff isort
        args: [check, --select, I, --fix]

      - id: ruff-format
        name: Ruff format

  - repo: https://github.com/windpioneers/pre-commit-hooks
    rev: 0.0.5
    hooks:
      - id: check-branch-name
        args:
          - "^main$"
          - "^([a-z][a-z0-9#]*)(-[a-z0-9#]+)*$"

  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.7.7
    hooks:
      - id: uv-lock

  # TODO Check for https://github.com/macisamuele/language-formatters-pre-commit-hooks/pull/252
  # and avoid sorting the project key halfway down the file.
  - repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
    rev: 'v2.14.0'
    hooks:
      - id: pretty-format-toml
        args: [--autofix]

  - repo: https://github.com/octue/conventional-commits
    rev: 0.9.0
    hooks:
      - id: check-commit-message-is-conventional
        stages: [commit-msg]

  - repo: https://github.com/thclark/pre-commit-sphinx
    rev: 0.0.3
    hooks:
      - id: build-docs
        language_version: python3
        additional_dependencies:
          - "."
