# Generated by Django 3.2.13 on 2022-04-15 20:04

import uuid

import django.db.models.deletion
import django_twined.fields
import django_twined.models.questions
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("django_twined", "0010_alter_servicerevision_project_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConcreteSynchronisedDatastore",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("a_string_tag", models.CharField(blank=True, help_text="A string tag", max_length=32)),
                (
                    "a_decimal_tag",
                    models.DecimalField(decimal_places=6, help_text="A decimal number tag", max_digits=10),
                ),
                (
                    "file",
                    django_twined.fields.DatafileObjectField(
                        help_text="Upload a data file which will have Octue metadata on it",
                        store_key="django-twined-concrete-store",
                        upload_to="",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QuestionWithValuesDatabaseStorage",
            fields=[
                (
                    "question_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="django_twined.question",
                    ),
                ),
            ],
            bases=(django_twined.models.questions.QuestionValuesDatabaseStorageMixin, "django_twined.question"),
        ),
    ]
