# Generated by Django 3.2.13 on 2022-10-12 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("example", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionwithvaluesdatabasestorage",
            name="apple_name",
            field=models.CharField(default="macintosh", help_text="Apple name", max_length=32),
        ),
        migrations.AddField(
            model_name="questionwithvaluesdatabasestorage",
            name="banana_name",
            field=models.CharField(default="chiquita", help_text="Banana name", max_length=32),
        ),
    ]
