FROM windpioneers/gdal-python:rational-swordtail-gdal-3.10.0-python-3.13-dev


# TO USE SYSTEM PYTHON
# Use a fixed project environment
ENV UV_PROJECT_ENVIRONMENT="/usr/local/"


# TO USE A VENV CACHED OUTSIDE THE DEVCONTAINER
# # Use a fixed project environment
# ENV UV_PROJECT_ENVIRONMENT="/workspace/.venv/"

# # Use fixed cache location on the same drive as the .venv (to enable symlinking)
# ENV UV_CACHE_DIR="/workspace/.uv_cache/"

# # Automatically source uv tools
# ENV PATH="/workspace/.venv/bin:$PATH"
