name: update-pr

on: [pull_request]

jobs:
  description:
    if: "!contains(github.event.head_commit.message, 'skipci')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          # Set fetch-depth to 0 to fetch all commit history (necessary for compiling pull request description).
          fetch-depth: 0

      - name: Generate PR description
        uses: octue/generate-pull-request-description@1.0.0.beta-0
        with:
          pull_request_url: ${{ github.event.pull_request.url }}
          api_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update pull request body
        uses: riskledger/update-pr-description@v2
        with:
          body: ${{ env.PULL_REQUEST_DESCRIPTION }}
          token: ${{ secrets.GITHUB_TOKEN }}
